name: Release

on:
  push:
    branches:
      - main

jobs:
  # Uses sematic-release to create release notes
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Get all history for tags
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
        run: npx -p semantic-release -p @semantic-release/github -p @semantic-release/release-notes-generator -p conventional-changelog-conventionalcommits semantic-release
